Detect IP

diff --git a/.github/workflows/fingertips-workflow.yml b/.github/workflows/fingertips-workflow.yml
--- a/.github/workflows/fingertips-workflow.yml
+++ b/.github/workflows/fingertips-workflow.yml
@@ -359,10 +359,24 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Get Public IP Address
-        id: get-ip
+      - name: Detect Public IP Address via SQLCMD
+        id: detect-ip
         run: |
-          echo "PUBLIC_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
+          export CONNECTION_STRING="Server=${{ secrets.AZURE_SQL_SERVER }},1433;Database=master;User Id=${{ secrets.AZURE_SQL_USER }};Password=${{ secrets.AZURE_SQL_PASSWORD }};Encrypt=True;TrustServerCertificate=False;"
+          
+          ERROR_MSG=$(sqlcmd -S ${{ secrets.AZURE_SQL_SERVER }} -U ${{ secrets.AZURE_SQL_USER }} -P ${{ secrets.AZURE_SQL_PASSWORD }} -d master -Q "SELECT 'Validating connection'" 2>&1 || true)
+          
+          echo "Raw SQLCMD Output: $ERROR_MSG"
+    
+          IP_REGEX='([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})'
+          if [[ $ERROR_MSG =~ $IP_REGEX ]]; then
+              CLIENT_IP="${BASH_REMATCH[1]}"
+              echo "Detected IP: $CLIENT_IP"
+              echo "CLIENT_IP=$CLIENT_IP" >> $GITHUB_ENV
+          else
+              echo "Failed to detect IP address. Exiting..."
+              exit 1
+          fi
     
       - name: Add Temporary Firewall Rule
         run: |
